### ISSUE TITLE
Synchronizing data using dropbox

### ISSUE THREAD

**Issue by kazup01** [BoostIO/boostnote-mobile#7]
Can sync data with desktop app.

**Comment by yashha** [comment]
WebDAV sync would also be awesome
Or sync with a folder in the local storage (internal, sdcard)

And it should only contact dropbox, when you really want to use it.

**Comment by ericvicenti** [comment]
Perhaps we could use DeepStreamHub, so that way we can get free remote syncing with `deepstreamhub.com` (see free plan with 1gb of storage [here](https://deepstreamhub.com/pricing/)). We should of course allow you to specify an arbitrary DSH server for those who want to self-host.

I've been looking for an excuse to play with DeepStreamHub, and boostnote looks like a cool project to contribute to. Would BoostIO be interested in a pull request for this?

**Comment by kohei-takata** [comment]
Now that we can use Dropbox sync.
So I close this issue.
If @yashha or @ericvicenti want to use another sync feature, please open another issue!
Thanks 😄
